'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
    Download, Link as LinkIcon, Check, ReceiptText, ClipboardList,
    AlertTriangle, AlertCircle, ChevronDown, CheckCircle2, Clock, CalendarDays,
    ChevronLeft, ChevronRight, Lock, FileSpreadsheet
} from 'lucide-react'
import { toPng } from 'html-to-image'
import NextLink from 'next/link'
import * as XLSX from 'xlsx'

type BillDetail = {
    id: string
    type: string
    cost: number
    paid: boolean
    due_date: string | null
}

type MealLogEntry = {
    date: string
    regular: number
    guest: number
}

type BreakdownItem = {
    id: string
    name: string
    meals: number
    regularMeals: number
    guestMeals: number
    activeDays: number
    mealCost: number
    utilityCost: number
    mealDeposits: number
    utilityDeposits: number
    mealBalance: number
    utilityBalance: number
    totalBalance: number
    billDetails: BillDetail[]
    mealLog: MealLogEntry[]
}

type DeadlineItem = {
    type: string
    due_date: string
    isOverdue: boolean
}

type UtilityBill = {
    id: string
    type: string
    cost: number
    due_date: string | null
}
type RawDeposit = {
    memberName: string
    type: string
    amount: number
    date: string
}


type SummaryProps = {
    monthName: string
    monthYear: string
    breakdown: BreakdownItem[]
    textSummary: string
    deadlines: DeadlineItem[]
    utilityBills: UtilityBill[]
    isLocked: boolean
    prevMonth: string
    nextMonth: string
    hasNextMonth: boolean
    rawDeposits: RawDeposit[]
    stats: {
        totalMeals: number
        mealRate: number
        totalGroceries: number
        totalUtilities: number
    }
}

// Format a YYYY-MM-DD date string to a friendly display: "Feb 25"
function fmtDate(dateStr: string) {
    return new Date(dateStr + 'T00:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
}

export default function SummaryClient({ monthName, monthYear, breakdown, textSummary, deadlines, utilityBills, isLocked, prevMonth, nextMonth, hasNextMonth, rawDeposits, stats }: SummaryProps) {
    const [isExporting, setIsExporting] = useState(false)
    const [isExportingXlsx, setIsExportingXlsx] = useState(false)
    const [copiedLink, setCopiedLink] = useState(false)
    const [copiedSummary, setCopiedSummary] = useState(false)
    const [expandedUtil, setExpandedUtil] = useState<Set<string>>(new Set())
    const [expandedLog, setExpandedLog] = useState<Set<string>>(new Set())

    // ── Excel helpers ─────────────────────────────────────────────────────────
    const buildWorkbook = (filterMemberId?: string) => {
        const wb = XLSX.utils.book_new()
        const brand = `Report Generated by SuperMeal | Developed by MayazAD`
        const label = `${monthName} — ${monthYear}`
        const filtered = filterMemberId ? breakdown.filter(b => b.id === filterMemberId) : breakdown

        // TAB 1: Meals
        const mealsRows: unknown[][] = [
            [brand, '', '', '', ''],
            [label, '', '', '', ''],
            ['Date', 'Member', 'Regular Meals', 'Guest Meals', 'Total Daily'],
        ]
        filtered.forEach(p =>
            p.mealLog.forEach(row =>
                mealsRows.push([row.date, p.name, row.regular, row.guest, row.regular + row.guest])
            )
        )
        mealsRows.push([], ['System Designed by MayazAD'])
        XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(mealsRows), 'Meals')

        // TAB 2: Utilities
        const utilRows: unknown[][] = [
            [brand, '', '', '', ''],
            [label, '', '', '', ''],
            ['Member', 'Bill Type', 'Total Bill (Tk)', 'Share (Tk)', 'Status'],
        ]
        filtered.forEach(p =>
            p.billDetails.forEach(b =>
                utilRows.push([
                    p.name, b.type,
                    b.cost.toFixed(2),
                    (b.cost / (breakdown.length || 1)).toFixed(2),
                    b.paid ? 'Paid' : 'Pending',
                ])
            )
        )
        utilRows.push([], ['System Designed by MayazAD'])
        XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(utilRows), 'Utilities')

        // TAB 3: Deposits
        const deps = filterMemberId
            ? rawDeposits.filter(d => {
                const p = breakdown.find(b => b.id === filterMemberId)
                return p ? d.memberName === p.name : false
            })
            : rawDeposits
        const depRows: unknown[][] = [
            [brand, '', '', ''],
            [label, '', '', ''],
            ['Member', 'Type', 'Amount (Tk)', 'Date'],
            ...deps.map(d => [d.memberName, d.type, d.amount.toFixed(2), d.date]),
            [],
            ['System Designed by MayazAD'],
        ]
        XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(depRows), 'Deposits')

        // TAB 4: Summary
        const sumRows: unknown[][] = [
            [brand, '', '', '', '', ''],
            [label, '', '', '', '', ''],
            ['Member', 'Total Meals', 'Meal Cost (Tk)', 'Meal Deposited (Tk)', 'Utility Share (Tk)', 'Utility Deposited (Tk)', 'Final Balance (Tk)', 'Status'],
        ]
        filtered.forEach(p => {
            const status = p.totalBalance < -0.01 ? 'Owes' : p.totalBalance > 0.01 ? 'Credit' : 'Settled'
            sumRows.push([
                p.name, p.meals,
                p.mealCost.toFixed(2), p.mealDeposits.toFixed(2),
                p.utilityCost.toFixed(2), p.utilityDeposits.toFixed(2),
                Math.abs(p.totalBalance).toFixed(2), status,
            ])
        })
        sumRows.push([], ['System Designed by MayazAD'])
        XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(sumRows), 'Summary')

        return wb
    }

    const handleExportExcel = () => {
        setIsExportingXlsx(true)
        try {
            const wb = buildWorkbook()
            XLSX.writeFile(wb, `SuperMeal_Report_MayazAD_${monthYear}.xlsx`)
        } catch (e) { console.error(e) } finally { setIsExportingXlsx(false) }
    }

    const handleMemberStatement = (memberId: string, memberName: string) => {
        try {
            const wb = buildWorkbook(memberId)
            XLSX.writeFile(wb, `SuperMeal_Statement_${memberName.replace(/\s+/g, '_')}_${monthYear}.xlsx`)
        } catch (e) { console.error(e) }
    }

    const toggleUtil = (id: string) => setExpandedUtil(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n })
    const toggleLog = (id: string) => setExpandedLog(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n })

    // Wall of Shame — members with negative total balance, sorted worst first
    const wallOfShame = breakdown
        .filter(p => p.totalBalance < -0.01)
        .sort((a, b) => a.totalBalance - b.totalBalance)

    const handleExport = async () => {
        const element = document.getElementById('summary-capture')
        if (!element) return
        setIsExporting(true)
        try {
            const dataUrl = await toPng(element, {
                pixelRatio: 2,
                backgroundColor: '#000000',
                filter: (node) => !(node instanceof HTMLElement && node.tagName === 'LINK'),
            })
            const link = document.createElement('a')
            link.href = dataUrl
            link.download = `SuperMeal_Summary_${monthYear}.png`
            link.click()
        } catch (err) {
            console.error('Image export failed:', err)
        } finally {
            setIsExporting(false)
        }
    }

    const handleCopyLink = () => {
        navigator.clipboard.writeText(window.location.href)
        setCopiedLink(true)
        setTimeout(() => setCopiedLink(false), 2000)
    }

    const handleCopyText = () => {
        navigator.clipboard.writeText(textSummary)
        setCopiedSummary(true)
        setTimeout(() => setCopiedSummary(false), 2000)
    }

    const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.08 } } }
    const item = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0, transition: { type: 'spring' as const, stiffness: 110 } } }
    const totalExpenses = stats.totalGroceries + stats.totalUtilities
    const [showRateTooltip, setShowRateTooltip] = useState(false)
    const perPersonUtility = breakdown.length > 0 ? stats.totalUtilities / breakdown.length : 0

    return (
        <div className="min-h-screen bg-background text-foreground py-10 px-4 sm:px-6">
            <div className="max-w-2xl mx-auto space-y-6">

                {/* Month Navigation */}
                <div className="flex items-center justify-between">
                    <NextLink href={`/summary/${prevMonth}`}
                        className="h-9 w-9 flex items-center justify-center rounded-lg border hover:bg-muted transition-colors">
                        <ChevronLeft className="h-4 w-4" />
                    </NextLink>
                    <span className="text-sm font-semibold tracking-wide">{monthName}</span>
                    <NextLink
                        href={hasNextMonth ? `/summary/${nextMonth}` : '#'}
                        aria-disabled={!hasNextMonth}
                        className={`h-9 w-9 flex items-center justify-center rounded-lg border transition-colors ${hasNextMonth ? 'hover:bg-muted' : 'opacity-30 pointer-events-none'}`}>
                        <ChevronRight className="h-4 w-4" />
                    </NextLink>
                </div>

                {/* Locked banner */}
                {isLocked && (
                    <div className="flex items-center gap-2 rounded-xl border border-foreground/20 bg-muted/40 px-4 py-2.5 text-sm">
                        <Lock className="h-4 w-4 shrink-0" />
                        <span className="font-medium">This month is <strong>locked</strong> — a permanent archived record.</span>
                    </div>
                )}

                {/* Top Bar */}
                <div className="flex flex-wrap items-center justify-between gap-3">
                    <div className="flex items-center gap-2 font-bold text-xl tracking-tight">
                        <div className="h-8 w-8 rounded bg-foreground text-background flex items-center justify-center text-sm font-black">M</div>
                        SuperMeal
                    </div>
                    <div className="flex flex-wrap gap-2">
                        <button onClick={handleCopyText} className="inline-flex h-9 items-center justify-center rounded-md border bg-transparent px-3 text-sm font-medium transition-colors hover:bg-muted">
                            {copiedSummary ? <Check className="h-4 w-4 mr-1.5" /> : <ClipboardList className="h-4 w-4 mr-1.5" />}
                            {copiedSummary ? 'Copied!' : 'Copy Breakdown'}
                        </button>
                        <button onClick={handleCopyLink} className="inline-flex h-9 items-center justify-center rounded-md border bg-transparent px-3 text-sm font-medium transition-colors hover:bg-muted">
                            {copiedLink ? <Check className="h-4 w-4 mr-1.5" /> : <LinkIcon className="h-4 w-4 mr-1.5" />}
                            {copiedLink ? 'Copied!' : 'Share Link'}
                        </button>
                        <button onClick={handleExport} disabled={isExporting} className="inline-flex h-9 items-center justify-center rounded-md bg-foreground text-background px-3 text-sm font-medium transition-colors hover:bg-foreground/90 disabled:opacity-50">
                            <Download className="h-4 w-4 mr-1.5" />
                            {isExporting ? 'Exporting…' : 'Save Image'}
                        </button>
                        <button onClick={handleExportExcel} disabled={isExportingXlsx} className="inline-flex h-9 items-center justify-center rounded-md border bg-transparent px-3 text-sm font-medium transition-colors hover:bg-muted disabled:opacity-50">
                            <FileSpreadsheet className="h-4 w-4 mr-1.5" />
                            {isExportingXlsx ? 'Building…' : 'Download Report'}
                        </button>
                    </div>
                </div>

                {/* Deadlines Banner */}
                <AnimatePresence>
                    {deadlines.length > 0 && (
                        <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-foreground/20 bg-muted/60 p-4 space-y-2">
                            <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-2">Upcoming Deadlines</p>
                            {deadlines.map((d, i) => (
                                <div key={i} className={`flex items-center gap-2 text-sm font-medium ${d.isOverdue ? 'text-red-500' : 'text-foreground'}`}>
                                    {d.isOverdue ? <AlertCircle className="h-4 w-4 shrink-0" /> : <AlertTriangle className="h-4 w-4 shrink-0 text-yellow-500" />}
                                    <span>
                                        {d.type}: Due {new Date(d.due_date).toLocaleDateString()}
                                        {d.isOverdue && <span className="ml-2 text-xs font-bold uppercase tracking-wide">— OVERDUE</span>}
                                    </span>
                                </div>
                            ))}
                        </motion.div>
                    )}
                </AnimatePresence>

                {/* Wall of Shame — pending collections */}
                <AnimatePresence>
                    {wallOfShame.length > 0 && (
                        <motion.div
                            initial={{ opacity: 0, y: -6 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0 }}
                            className="rounded-xl border border-red-400/30 bg-red-50/30 dark:bg-red-950/20 px-4 py-3"
                        >
                            <p className="text-[10px] font-bold uppercase tracking-widest text-red-500 mb-2">⚠ Pending Collections</p>
                            <div className="flex flex-wrap gap-2">
                                {wallOfShame.map(p => (
                                    <span key={p.id} className="inline-flex items-center gap-1 text-xs font-medium bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-full px-2.5 py-1">
                                        {p.name} — {Math.abs(p.totalBalance).toFixed(0)} Tk
                                    </span>
                                ))}
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>

                {/* Receipt Card */}
                <motion.div id="summary-capture" variants={container} initial="hidden" animate="show"
                    className="rounded-2xl border bg-card text-card-foreground shadow-sm p-6 sm:p-10 relative overflow-hidden">
                    <div className="absolute top-0 right-0 -mr-16 -mt-16 w-64 h-64 bg-foreground/5 rounded-full blur-3xl pointer-events-none" />

                    {/* Header */}
                    <motion.div variants={item} className="text-center space-y-2 mb-8 pb-6 border-b border-dashed">
                        <div className="inline-flex items-center justify-center p-3 bg-muted rounded-full mb-2">
                            <ReceiptText className="h-6 w-6" />
                        </div>
                        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight uppercase">Monthly Summary</h1>
                        <p className="text-muted-foreground font-medium">{monthName}</p>
                    </motion.div>

                    {/* Quick Stats */}
                    <motion.div variants={item} className="grid grid-cols-2 gap-4 mb-8">
                        <div>
                            <div className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">Total House Expenses</div>
                            <div className="text-2xl font-bold">{totalExpenses.toFixed(2)} Tk</div>
                            <div className="text-xs text-muted-foreground mt-1">Meal: {stats.totalGroceries.toFixed(2)} + Utility: {stats.totalUtilities.toFixed(2)} Tk</div>
                        </div>
                        <div className="text-right">
                            <div className="flex items-center justify-end gap-1 text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
                                Meal Rate
                                {/* (i) tooltip */}
                                <div className="relative">
                                    <button
                                        onMouseEnter={() => setShowRateTooltip(true)}
                                        onMouseLeave={() => setShowRateTooltip(false)}
                                        onClick={() => setShowRateTooltip(v => !v)}
                                        aria-label="How meal rate is calculated"
                                        className="ml-0.5 h-4 w-4 rounded-full border border-muted-foreground/50 text-muted-foreground flex items-center justify-center text-[9px] font-bold hover:border-foreground hover:text-foreground transition-colors"
                                    >i</button>

                                    <AnimatePresence>
                                        {showRateTooltip && (
                                            <>
                                                {/* Mobile: fixed full-screen backdrop + centered card */}
                                                <motion.div
                                                    key="backdrop"
                                                    initial={{ opacity: 0 }}
                                                    animate={{ opacity: 1 }}
                                                    exit={{ opacity: 0 }}
                                                    className="sm:hidden fixed inset-0 z-[99] bg-black/50"
                                                    onClick={() => setShowRateTooltip(false)}
                                                />
                                                <motion.div
                                                    key="tooltip-mobile"
                                                    initial={{ opacity: 0, scale: 0.96, y: 8 }}
                                                    animate={{ opacity: 1, scale: 1, y: 0 }}
                                                    exit={{ opacity: 0, scale: 0.96 }}
                                                    className="sm:hidden fixed left-4 right-4 bottom-6 z-[100] rounded-2xl bg-zinc-950 border border-zinc-800 text-zinc-100 shadow-2xl p-5"
                                                >
                                                    <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-400 mb-2">How It&apos;s Calculated</p>
                                                    <p className="text-sm font-semibold leading-relaxed">Total Grocery Cost ÷ Total Meals Consumed</p>
                                                    <div className="mt-3 pt-3 border-t border-zinc-800 space-y-1">
                                                        <div className="flex justify-between text-xs text-zinc-400 leading-relaxed">
                                                            <span>Grocery Cost</span>
                                                            <span className="font-mono">{stats.totalGroceries.toFixed(2)} Tk</span>
                                                        </div>
                                                        <div className="flex justify-between text-xs text-zinc-400 leading-relaxed">
                                                            <span>Total Meals</span>
                                                            <span className="font-mono">{stats.totalMeals}</span>
                                                        </div>
                                                        <div className="flex justify-between text-sm font-bold text-white border-t border-zinc-700 pt-2 mt-1">
                                                            <span>Meal Rate</span>
                                                            <span className="font-mono">{stats.mealRate.toFixed(2)} Tk</span>
                                                        </div>
                                                    </div>
                                                    <button onClick={() => setShowRateTooltip(false)} className="mt-3 w-full text-xs text-zinc-500 hover:text-zinc-300 transition-colors">Tap to close</button>
                                                </motion.div>

                                                {/* Desktop: absolute centered tooltip with caret */}
                                                <motion.div
                                                    key="tooltip-desktop"
                                                    initial={{ opacity: 0, y: 6 }}
                                                    animate={{ opacity: 1, y: 0 }}
                                                    exit={{ opacity: 0 }}
                                                    transition={{ duration: 0.15 }}
                                                    className="hidden sm:block absolute top-7 left-1/2 -translate-x-1/2 z-[100] rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100 shadow-2xl p-4"
                                                    style={{ minWidth: '280px', maxWidth: '350px' }}
                                                >
                                                    {/* Caret arrow pointing up */}
                                                    <div className="absolute -top-[7px] left-1/2 -translate-x-1/2 w-3 h-3 bg-zinc-950 border-l border-t border-zinc-800 rotate-45" />

                                                    <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-400 mb-2">How It&apos;s Calculated</p>
                                                    <p className="text-sm font-semibold leading-relaxed">Total Grocery Cost ÷ Total Meals Consumed</p>
                                                    <div className="mt-3 pt-3 border-t border-zinc-800 space-y-1">
                                                        <div className="flex justify-between text-xs text-zinc-400 leading-relaxed">
                                                            <span>Grocery Cost</span>
                                                            <span className="font-mono">{stats.totalGroceries.toFixed(2)} Tk</span>
                                                        </div>
                                                        <div className="flex justify-between text-xs text-zinc-400 leading-relaxed">
                                                            <span>Total Meals</span>
                                                            <span className="font-mono">{stats.totalMeals}</span>
                                                        </div>
                                                        <div className="flex justify-between text-sm font-bold text-white border-t border-zinc-700 pt-2 mt-1">
                                                            <span>= Meal Rate</span>
                                                            <span className="font-mono">{stats.mealRate.toFixed(2)} Tk</span>
                                                        </div>
                                                    </div>
                                                </motion.div>
                                            </>
                                        )}
                                    </AnimatePresence>
                                </div>
                            </div>
                            <div className="text-2xl font-bold">{stats.mealRate.toFixed(2)} Tk</div>
                            <div className="text-xs text-muted-foreground mt-1">{stats.totalMeals} total meals (incl. guests)</div>
                        </div>
                    </motion.div>

                    <motion.h3 variants={item} className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-4">
                        Balances — Who Owes What
                    </motion.h3>

                    {/* Per-Person Cards */}
                    <div className="space-y-4">
                        <AnimatePresence>
                            {breakdown.map((person) => {
                                const mealNeg = person.mealBalance < -0.01
                                const utilNeg = person.utilityBalance < -0.01
                                const totalPos = person.totalBalance > 0.01
                                const totalNeg = person.totalBalance < -0.01
                                const hasOverdue = utilNeg && deadlines.some(d => d.isOverdue)
                                const isUtilExpanded = expandedUtil.has(person.id)
                                const isLogExpanded = expandedLog.has(person.id)
                                const paidCount = person.billDetails.filter(b => b.paid).length

                                return (
                                    <motion.div key={person.id} variants={item} layout className="rounded-xl bg-muted/30 border overflow-hidden">
                                        <div className="p-4 space-y-3">
                                            {/* Name + Balance */}
                                            <div className="flex items-start justify-between gap-4">
                                                <div>
                                                    <p className="font-bold text-lg leading-tight">{person.name}</p>
                                                    <p className="text-xs text-muted-foreground mt-0.5">
                                                        {person.meals} meals · {person.activeDays} active days · {person.guestMeals} guest
                                                    </p>
                                                </div>
                                                <div className="text-right shrink-0 space-y-1">
                                                    <div className={`text-xl font-bold ${totalPos ? 'text-green-500' : totalNeg ? 'text-red-500' : 'text-muted-foreground'}`}>
                                                        {person.totalBalance > 0 ? '+' : ''}{person.totalBalance.toFixed(2)} Tk
                                                    </div>
                                                    {/* Status badge */}
                                                    <span className={`inline-block text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full ${totalPos ? 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300'
                                                        : totalNeg ? 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300'
                                                            : 'bg-muted text-muted-foreground'
                                                        }`}>
                                                        {totalPos ? '✓ In Credit' : totalNeg ? 'Needs to Pay' : '✓ Settled'}
                                                    </span>
                                                </div>
                                            </div>

                                            {/* Fund Breakdown */}
                                            <div className="grid grid-cols-2 gap-3 text-xs">
                                                <div className="bg-background/60 border rounded-lg p-2.5 space-y-1">
                                                    <div className="font-semibold uppercase tracking-wide text-muted-foreground mb-1">Meal Fund</div>
                                                    <div className="flex justify-between"><span>Deposited</span><span>{person.mealDeposits.toFixed(2)} Tk</span></div>
                                                    <div className="flex justify-between"><span>Cost</span><span>−{person.mealCost.toFixed(2)} Tk</span></div>
                                                    <div className={`flex justify-between font-bold border-t pt-1 mt-1 ${mealNeg ? 'text-red-500' : 'text-green-500'}`}>
                                                        <span>Balance</span><span>{person.mealBalance > 0 ? '+' : ''}{person.mealBalance.toFixed(2)} Tk</span>
                                                    </div>
                                                </div>
                                                <div className="bg-background/60 border rounded-lg p-2.5 space-y-1">
                                                    <div className="font-semibold uppercase tracking-wide text-muted-foreground mb-1">Utility Fund</div>
                                                    <div className="flex justify-between"><span>Deposited</span><span>{person.utilityDeposits.toFixed(2)} Tk</span></div>
                                                    <div className="flex justify-between"><span>Share</span><span>−{person.utilityCost.toFixed(2)} Tk</span></div>
                                                    <div className={`flex justify-between font-bold border-t pt-1 mt-1 ${utilNeg ? 'text-red-500' : 'text-green-500'}`}>
                                                        <span>Balance</span><span>{person.utilityBalance > 0 ? '+' : ''}{person.utilityBalance.toFixed(2)} Tk</span>
                                                    </div>
                                                </div>
                                            </div>

                                            {/* Expand buttons row */}
                                            <div className="flex flex-wrap gap-2">
                                                {/* Bill Details toggle */}
                                                {person.billDetails.length > 0 && (
                                                    <button onClick={() => toggleUtil(person.id)}
                                                        className="flex items-center justify-between px-3 py-2 text-xs font-medium rounded-lg border bg-background/40 hover:bg-background/70 transition-colors">
                                                        <span className="text-muted-foreground">Bills ({paidCount}/{person.billDetails.length})</span>
                                                        <motion.span animate={{ rotate: isUtilExpanded ? 180 : 0 }} transition={{ duration: 0.2 }}>
                                                            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
                                                        </motion.span>
                                                    </button>
                                                )}

                                                {/* Meal Log toggle */}
                                                {person.mealLog.length > 0 && (
                                                    <button onClick={() => toggleLog(person.id)}
                                                        className="flex items-center justify-between px-3 py-2 text-xs font-medium rounded-lg border bg-background/40 hover:bg-background/70 transition-colors">
                                                        <span className="text-muted-foreground flex items-center gap-1">
                                                            <CalendarDays className="h-3 w-3" /> Meal Log
                                                        </span>
                                                        <motion.span animate={{ rotate: isLogExpanded ? 180 : 0 }} transition={{ duration: 0.2 }}>
                                                            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
                                                        </motion.span>
                                                    </button>
                                                )}

                                                {/* My Statement download */}
                                                <button
                                                    onClick={() => handleMemberStatement(person.id, person.name)}
                                                    className="flex items-center justify-center gap-1.5 px-3 py-2 text-xs font-medium rounded-lg border bg-background/40 hover:bg-background/70 transition-colors col-span-2 sm:col-span-1"
                                                >
                                                    <FileSpreadsheet className="h-3 w-3" />
                                                    My Statement (.xlsx)
                                                </button>
                                            </div>

                                            {/* Smart Warnings */}
                                            <div className="space-y-1">
                                                {mealNeg && (
                                                    <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-600 dark:text-amber-400">
                                                        <AlertTriangle className="h-3.5 w-3.5 shrink-0" /> ⚠️ Meal Fund Low: Please top up.
                                                    </div>
                                                )}
                                                {utilNeg && !hasOverdue && (
                                                    <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-600 dark:text-amber-400">
                                                        <AlertTriangle className="h-3.5 w-3.5 shrink-0" /> ⚠️ Utility Due: Please pay your share.
                                                    </div>
                                                )}
                                                {hasOverdue && (
                                                    <div className="flex items-center gap-1.5 text-xs font-bold text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 rounded-md px-2 py-1">
                                                        <AlertCircle className="h-3.5 w-3.5 shrink-0" /> 🚨 OVERDUE: Pay Immediately.
                                                    </div>
                                                )}
                                            </div>
                                        </div>

                                        {/* Expandable: Bill Details */}
                                        <AnimatePresence initial={false}>
                                            {isUtilExpanded && (
                                                <motion.div key="bills" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                                                    exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25, ease: 'easeInOut' }} className="overflow-hidden">
                                                    <div className="border-t bg-background/30 px-4 py-3 space-y-2">
                                                        <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Utility Bill Breakdown</p>
                                                        {person.billDetails.map(bill => {
                                                            const pp = breakdown.length > 0 ? bill.cost / breakdown.length : 0
                                                            return (
                                                                <div key={bill.id} className={`flex items-center justify-between rounded-lg px-3 py-2 text-xs ${bill.paid ? 'bg-foreground/5 border border-foreground/10' : 'bg-background/60 border border-dashed border-muted-foreground/30'}`}>
                                                                    <div className="flex items-center gap-2">
                                                                        {bill.paid ? <CheckCircle2 className="h-4 w-4 shrink-0 text-green-500" /> : <Clock className="h-4 w-4 shrink-0 text-amber-500" />}
                                                                        <span className="font-medium">{bill.type}</span>
                                                                        <span className="text-muted-foreground">{bill.cost.toFixed(0)} Tk</span>
                                                                    </div>
                                                                    <div className="flex items-center gap-2">
                                                                        <span className="text-muted-foreground">{pp.toFixed(2)} Tk/person</span>
                                                                        <span className={`font-bold ${bill.paid ? 'text-green-500' : 'text-amber-500'}`}>{bill.paid ? '✅ Paid' : '⏳ Pending'}</span>
                                                                    </div>
                                                                </div>
                                                            )
                                                        })}
                                                        <p className="text-[10px] text-muted-foreground pt-1">
                                                            Total share: {perPersonUtility.toFixed(2)} Tk/person
                                                        </p>
                                                    </div>
                                                </motion.div>
                                            )}
                                        </AnimatePresence>

                                        {/* Expandable: Meal Log */}
                                        <AnimatePresence initial={false}>
                                            {isLogExpanded && (
                                                <motion.div key="log" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                                                    exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25, ease: 'easeInOut' }} className="overflow-hidden">
                                                    <div className="border-t bg-background/30 px-4 py-3 space-y-1.5">
                                                        <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-2">
                                                            Meal Calendar — {monthName}
                                                        </p>
                                                        {person.mealLog.map(entry => (
                                                            <div key={entry.date} className="flex items-center justify-between text-xs rounded-md px-2 py-1.5 bg-background/60 border">
                                                                <span className="font-mono font-medium text-muted-foreground">{fmtDate(entry.date)}</span>
                                                                <div className="flex items-center gap-3">
                                                                    <span>{entry.regular} Regular</span>
                                                                    {entry.guest > 0 && <span className="text-muted-foreground">+ {entry.guest} Guest</span>}
                                                                </div>
                                                            </div>
                                                        ))}
                                                        <p className="text-[10px] text-muted-foreground pt-1">
                                                            {person.activeDays} active days · {person.meals} total meals
                                                        </p>
                                                    </div>
                                                </motion.div>
                                            )}
                                        </AnimatePresence>
                                    </motion.div>
                                )
                            })}
                        </AnimatePresence>
                    </div>

                    <motion.div variants={item} className="mt-8 pt-6 border-t border-dashed text-center text-xs text-muted-foreground">
                        Utility: {stats.totalUtilities.toFixed(2)} Tk ÷ {breakdown.length} members = {perPersonUtility.toFixed(2)} Tk/person
                    </motion.div>

                    {/* Signature Strip */}
                    <div className="mt-6 pt-4 border-t flex items-center justify-between gap-2">
                        <span className="text-[10px] text-muted-foreground/70 tracking-wide font-medium">Official Summary&nbsp;|&nbsp;SuperMeal App</span>
                        <span className="text-[10px] font-mono font-semibold text-muted-foreground/70 tracking-wide">Developer:&nbsp;MayazAD</span>
                    </div>
                </motion.div>

                <p className="text-center text-[11px] text-muted-foreground/40 tracking-wide pb-6">
                    © 2026 SuperMeal&nbsp;&nbsp;|&nbsp;&nbsp;Crafted by <span className="font-mono font-semibold">MayazAD</span>
                </p>
            </div>
        </div>
    )
}
